use_index_title: true
flatten_single_child_sections: true

sort:
  sections: mixed

nav:
  - Home: 01-home
  - Perseus V3:
      - Getting Started: 02-perseus-v3/01-getting-started
      - Challenge Tasks: 02-perseus-v3/02-challenge-tasks
      - Standards:       02-perseus-v3/03-standards
      - Tutorials:       02-perseus-v3/04-tutorials
      - Software:        02-perseus-v3/05-software
      - Firmware:        02-perseus-v3/06-firmware
      - Electrical:      02-perseus-v3/07-electrical
      - Hardware:        02-perseus-v3/08-hardware
  - Archive:
    - About: 03-archive
