# Use the "title" field in the index.md preamble for folder titles
use_index_title: true

# Flatten directories with a single markdown file into a single page
# This is useful to group images and static elements with a single markdown file
flatten_single_child_sections: true

# This allows folders and files to be sorted in the correct order
sort:
  sections: mixed

# The nav section is the main purpose of this plugin. We do not use it since in favour
# of ordering files manually and setting titles so the file structure reflects what is rendered.
# nav:
